# Generated by Django 5.2.14 on 2026-05-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('sql', 'SQL'), ('txt', 'Text')], max_length=20)),
                ('path', models.CharField(max_length=300)),
                ('departments', models.JSONField(default=list)),
                ('allowed_roles', models.JSONField(default=list)),
                ('min_clearance', models.IntegerField(default=1)),
                ('sensitivity', models.CharField(default='internal', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=80)),
                ('clearance', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QueryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('routed_sources', models.JSONField(default=list)),
                ('blocked_sources', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.enterpriseuser')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('page', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.datasource')),
            ],
            options={
                'unique_together': {('source', 'chunk_index')},
            },
        ),
    ]
