# Generated by Django 5.2.14 on 2026-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('sql', 'SQL'), ('txt', 'Text'), ('image', 'Image')], max_length=20),
        ),
    ]
